<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Data\TestDataTable_Full.sql" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Data\TestDataMocking\CreateTestData.sql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Syncfusion.Blazor.DataForm"		Version="29.1.38" />
		<PackageReference Include="Syncfusion.Blazor.Navigations"	Version="29.1.38" />
		<PackageReference Include="Syncfusion.Blazor.Themes"		Version="29.1.38" />
		<PackageReference Include="Syncfusion.Blazor.DropDowns"		Version="29.1.38" />
		<PackageReference Include="Syncfusion.Blazor.Grid"			Version="29.1.38" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AppConst\AppConst.csproj" />
	  <ProjectReference Include="..\SfDocFilter.BO\SfDocFilter.BO.csproj" />
	  <ProjectReference Include="..\SfDocFilter.DalMock\SfDocFilter.DalMock.csproj" />
	  <ProjectReference Include="..\SfDocFilter.DalSqlite\SfDocFilter.DalSqlite.csproj" />
	  <ProjectReference Include="..\SfDocFilter.DalSql\SfDocFilter.DalSql.csproj" />
	  <ProjectReference Include="..\SfDocFilter.Dal\SfDocFilter.Dal.csproj" />
	</ItemGroup>

</Project>
